:swift_library //HelloWorld:HelloWorldLib*™Dios_sim_arm64-dbg-ios-sim_arm64-min17.0-applebin_ios-ST-faa571ec622fios_sim_arm64"@604845167dc010f09949b2428d826ae6495e5a888d2bc1b075d74c5b5f033cbbä@893b0cb3679aa11935098e946d69dbff25a41809afd1d0b510275b7193a2d588"SwiftCompile(2]bazel-out/darwin_arm64-opt-exec-ST-d57f47055a04/bin/external/rules_swift+/tools/worker/worker2swiftc2-target2arm64-apple-ios17.0-simulator2-sdk2__BAZEL_XCODE_SDKROOT__2-debug-prefix-map28__BAZEL_XCODE_DEVELOPER_DIR__=/PLACEHOLDER_DEVELOPER_DIR2-file-prefix-map28__BAZEL_XCODE_DEVELOPER_DIR__=/PLACEHOLDER_DEVELOPER_DIR2@-Xwrapped-swift=-bazel-target-label=@@//HelloWorld:HelloWorldLib2-emit-object2-output-file-map2€bazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min17.0-applebin_ios-ST-faa571ec622f/bin/HelloWorld/HelloWorldLib.output_file_map.json2
-Xfrontend2-no-clang-module-breadcrumbs2-emit-module-path2wbazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min17.0-applebin_ios-ST-faa571ec622f/bin/HelloWorld/HelloWorldLib.swiftmodule2-enforce-exclusivity=checked2-emit-const-values-path2©bazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min17.0-applebin_ios-ST-faa571ec622f/bin/HelloWorld/HelloWorldLib_objs/HelloWorldLib/Sources/AddTodoView.swift.swiftconstvalues2
-Xfrontend2-const-gather-protocols-file2
-Xfrontend2Lexternal/rules_swift+/swift/toolchains/config/const_protocols_to_gather.json2-DDEBUG2-Onone2
-Xfrontend2-internalize-at-link2
-Xfrontend2-no-serialize-debugging-options2-enable-testing2-disable-sandbox2-g2'-Xwrapped-swift=-file-prefix-pwd-is-dot2%-Xwrapped-swift=-emit-swiftsourceinfo2-module-cache-path2fbazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min17.0-applebin_ios-ST-faa571ec622f/bin/_swift_module_cache2_-Ibazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min17.0-applebin_ios-ST-faa571ec622f/bin/HelloWorld2¡-Xwrapped-swift=-macro-expansion-dir=bazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min17.0-applebin_ios-ST-faa571ec622f/bin/HelloWorld/HelloWorldLib.macro-expansions2-Xcc2-iquote.2-Xcc2Y-iquotebazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min17.0-applebin_ios-ST-faa571ec622f/bin2-Xcc2E-fmodule-map-file=HelloWorld/TodoObjCSupport/Sources/module.modulemap2
-Xfrontend2-color-diagnostics2-enable-batch-mode2-module-name2HelloWorldLib2-file-prefix-map2+__BAZEL_XCODE_DEVELOPER_DIR__=DEVELOPER_DIR2-index-store-path2vbazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min17.0-applebin_ios-ST-faa571ec622f/bin/HelloWorld/HelloWorldLib.indexstore2-index-ignore-system-modules2M-Xwrapped-swift=-global-index-store-import-path=bazel-out/_global_index_store2-enable-bare-slash-regex2
-Xfrontend2-disable-clang-spi2-enable-experimental-feature2AccessLevelOnImport2-parse-as-library2-static2-Xcc2-O02-Xcc2	-DDEBUG=12-Xcc2-fstack-protector2-Xcc2-fstack-protector-all22HelloWorld/HelloWorldLib/Sources/AddTodoView.swift24HelloWorld/HelloWorldLib/Sources/HelloWorldApp.swift22HelloWorld/HelloWorldLib/Sources/TodoItemRow.swift23HelloWorld/HelloWorldLib/Sources/TodoListView.swift:'
XCODE_VERSION_OVERRIDE16.3.0.16E140:%
APPLE_SDK_PLATFORMiPhoneSimulator:"
APPLE_SDK_VERSION_OVERRIDE18.4Z
requires-darwinZ 
requires-worker-protocoljsonZ
supports-workers1Z!
supports-xcode-requirements-setr@@platforms//host:host